#!/usr/bin/env python3
"""Gzip the dashboard HTML from src/page.h into src/page_gz.h (PROGMEM array).

Runs as a PlatformIO pre-build script (extra_scripts in platformio.ini) before
every compile, so the compressed copy can never go stale against page.h.
Output is deterministic (mtime=0): identical page.h rebuilds byte-identical.

The "/" handler serves this with Content-Encoding: gzip when the client offers
it (all browsers do), falling back to the raw PROGMEM page otherwise.
"""
import gzip
import os
import pathlib
import re
import sys

try:
    proj = env.subst("$PROJECT_DIR")     # PlatformIO pre-script context injects `env`
except NameError:
    proj = os.getcwd()                   # standalone run: pio always executes from the project dir
src = pathlib.Path(proj) / "src" / "page.h"
out = pathlib.Path(proj) / "src" / "page_gz.h"

text = src.read_text(encoding="utf-8")
m = re.search(r'R"HTML\((.*)\)HTML"', text, re.S)
if not m:
    sys.exit("gen_page_gz: R\"HTML(...)\"HTML\" literal not found in page.h")
html = m.group(1).encode("utf-8")
gz = gzip.compress(html, 9, mtime=0)

with out.open("w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by tools/gen_page_gz.py -- do not edit.\n")
    f.write(f"// gzip -9 of the {len(html)} B dashboard HTML in src/page.h ({len(gz)} B compressed).\n")
    f.write("#include <pgmspace.h>\n\n")
    f.write("const unsigned char PAGE_GZ[] PROGMEM = {\n")
    for i in range(0, len(gz), 20):
        f.write(", ".join(f"0x{b:02X}" for b in gz[i:i + 20]) + ",\n")
    f.write("};\n")
    f.write(f"const size_t PAGE_GZ_LEN = {len(gz)};\n")

print(f"gen_page_gz: {len(html)} B html -> {len(gz)} B gz ({100 * len(gz) // max(len(html), 1)}%) -> page_gz.h")
